# Generated by Django 3.0.3 on 2020-02-16 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='site',
            field=models.CharField(default='tmp', max_length=5),
            preserve_default=False,
        ),
    ]
