# Generated by Django 3.0.3 on 2020-02-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0005_job_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published',
            field=models.DateTimeField(default=None),
        ),
    ]
