# Generated by Django 3.0.3 on 2020-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agg', '0006_auto_20200216_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
